- name: Generate script.
  ansible.builtin.template:
    src: darwin-rebuild.exp.j2
    dest: "~/.darwin-rebuild.exp"
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: "0700"

- name: Run script.
  ansible.builtin.command: "~/.darwin-rebuild.exp"

- name: Remove script.
  ansible.builtin.file:
    path: "~/.darwin-rebuild.exp"
    state: absent
