- name: Create config dir.
  ansible.builtin.file:
    path: "{{ xdg_config_home }}/nixpkgs"
    state: directory
    owner: "{{ username }}"
    group: "{{ group }}"

- name: Generate config (Linux).
  ansible.builtin.template:
    src: config.nix.j2
    dest: "{{ xdg_config_home }}/nixpkgs/config.nix"
    owner: "{{ username }}"
    group: "{{ group }}"
  notify: Rebuild nix (Linux).
